clear;close all;clc;
addpath(genpath('.\.'));

%% print the table for step function
load('ResultSynA.mat');
fprintf('Result for Synthetic A data set\n');
res = cRes.Test;
printStat([],res);

%% for functions generated by GP
fprintf('\n');
strFile = {'ResultSynGPA.mat','ResultSynGPB.mat'};
cPre = cell(1,length(strFile));
for i = 1:length(strFile)
    load(strFile{i});
    fprintf('Result for Synthetic GP data set\n');
    res = cRes.Test;
    printStat([],res);
end